// src/routes/about.svelte
<script>
	import text from '~/styles/text.module.css';
	import link from '~/styles/link.module.css';
</script>

<div class="space-lg" />
<section class="section">
	<img src="/bio@2x.png" alt="lynn" class="bio" title="🦀 🦁 🦂 😉" />
	<div>
		<h3 class={text.heading}>About the developer</h3>
		<div>
			<p class={text.base}>
				I'm a biology & psychology grad with a day job in public insurance
				services, but I dream of finding a home in tech where I can help keep
				this beautiful space open, inclusive, human-centered & adventurous.
			</p>

			<p class={text.base}>
				I love oat lattes, minimalism, pair programming with my partner <a
					href="https://twitter.com/mvllow"
					class={link.inline}>@mvllow</a
				>, and exploring personal disciplines. Some of these at the moment
				include sustainability, daily yoga practice, running, vegan ethics, &
				living car-free.
			</p>
		</div>
	</div>
	<p class={text.base}>
		My <a href="https://twitter.com/fvrests" class={link.inline}>twitter</a> is
		always open to DMs, suggestions & friend requests, & I love
		<a href="mailto:fvrests@icloud.com" class={link.inline}>emails</a> as well 🥰
		Message me about your ideas, what you're working on or anything on your mind!
	</p>
</section>

<style>
	.bio {
		width: 150px;
		border-radius: 4px;
		margin: 0.25em 0 36px 0;
	}
	@media (min-width: 600px) {
		.bio {
			float: left;
			margin-right: calc(8px + 8px + 1.5em);
			margin-bottom: 8px;
		}
	}
</style>

// pages/about.vue
<template>
	<Section>
		<div class="max-w-prose md:max-w-none mx-auto mb-8">
			<Heading>
				About me
			</Heading>
		</div>

		<div class="sm:space-x-12 flex flex-col sm:flex-row">
			<div class="flex-1">
				<div class="mb-8 max-w-56 sm:max-w-none w-full">
					<img
						src="/portrait.png"
						class="w-full max-w-prose mx-auto border-8 object-cover border-border relative z-20 rounded-xl"
					/>
				</div>
			</div>
			<BaseText class="flex-1 text-fgSubtle">
				I'm a biology and psychology grad migrating to web dev. I love
				oat lattes, building things that are both functional and pastel,
				pair programming with my partner
				<TextLink url="https://twitter.com/mvllow">@mvllow</TextLink>,
				and working on hobbies and disciplines. Some of those at the
				moment include:
				<CapsuleList
					:items="[
						{ symbol: '🧺', text: 'minimalism' },
						{ symbol: '🧘🏼‍♀️', text: 'daily yoga practice' },
						{ symbol: '🐷', text: 'ethical veganism' },
						{
							symbol: '🌱',
							text: 'sustainable & slow living',
						},
						{ symbol: '🚲', text: 'living car-free' },
						{ symbol: '🌳', text: 'slacklining' },
					]"
				/>I'm motivated by a sense of community and love building
				connections, so my
				<TextLink url="https://twitter.com/fvrests/"
					>Twitter DMs</TextLink
				>
				are always open to suggestions, requests & friends 💛
			</BaseText>
		</div>
	</Section>
</template>
